#Github Actions to trigger Terraform Cloud and provision using AZ
name: 'Deploy Action'

on:
  push:
    branches:
    - master
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    # Checkout the repository to the GitHub Actions runner
    steps:
    - name: Checkout
      uses: actions/checkout@v2

   
    
    
    #API Call to Terraform.io to get app-services name
    - name: Get App Variable Name
      run: |
           echo ${{ secrets.TF_ENV }} >> test.txt
           cat test.txt
           out=$(curl --header "Authorization: Bearer ${{ secrets.TERRAFORM }}" --header "Content-Type: application/vnd.api+json" ${{ secrets.TF_ENV }} | jq -c --arg key "victim-company" '.data[].attributes | select (.key=="victim_company") | .value')
           out=$(echo $out | tr -d \")
           out1="$out-app-service"
           out2="$out-rg"
           echo ::set-env name=APP_NAME::$(echo $out1)
           echo ::set-env name=RG::$(echo $out2)
      
  
           
         
           

    
   
